'use strict';
const fs=require('node:fs'),path=require('node:path');
// Optional diagnostic after frame samples have already been collected; never changes the gate result.
module.exports=async function(call,dir){
  if(process.env.TM_BRIDGE_TACTICAL_PROFILE!=='1')return;
  const r=await call(`(()=>{const gl=R3D.context,saved={render:R3D.render,drawUnits:R3D.drawUnits,crowd:updateMenCrowd},samples={render:[],drawUnits:[],crowd:[],total:[]};for(const k of ['render','drawUnits'])R3D[k]=function(...a){gl.finish();const t=performance.now(),r=saved[k].apply(this,a);gl.finish();samples[k].push(performance.now()-t);return r;};updateMenCrowd=function(){const t=performance.now();saved.crowd();samples.crowd.push(performance.now()-t);};try{for(let i=0;i<3;i++){const t=performance.now();draw();gl.finish();samples.total.push(performance.now()-t);}}finally{R3D.render=saved.render;R3D.drawUnits=saved.drawUnits;updateMenCrowd=saved.crowd;}samples.cache=R3D.frameCacheStats;return samples;})()`);
  fs.writeFileSync(path.join(dir,'pipeline-profile.json'),JSON.stringify(r,null,2));
  const layers=await call(`(async()=>{const out={diagnosticOnly:true,hudFlush:[],parent:{canvases:[...parent.document.querySelectorAll('canvas')].map(c=>({id:c.id,w:c.width,h:c.height,visible:!!c.getClientRects().length})),animations:parent.document.getAnimations().length}};for(let i=0;i<3;i++){draw();const t=performance.now();_cvCtx.getImageData(0,0,cv.width,cv.height);out.hudFlush.push(performance.now()-t);}const sample=()=>new Promise(resolve=>{const a=[];let last=performance.now();function tick(now){a.push(now-last);last=now;if(a.length===20){a.sort((x,y)=>x-y);resolve({median:a[10],p95:a[18]});}else requestAnimationFrame(tick);}requestAnimationFrame(tick);});const original=draw,render=R3D.render,drawUnits=R3D.drawUnits,crowd=updateMenCrowd;try{draw=()=>{};await sample();out.noDraw=await sample();draw=original;updateMenCrowd=()=>{};out.noCrowd=await sample();updateMenCrowd=crowd;R3D.render=()=>{};R3D.drawUnits=()=>{};out.noGL=await sample();R3D.render=render;R3D.drawUnits=drawUnits;draw=()=>{R3D.render();R3D.drawUnits(buildUnitInstances());};out.onlyGL=await sample();draw=original;out.restored=await sample();return out;}finally{draw=original;R3D.render=render;R3D.drawUnits=drawUnits;updateMenCrowd=crowd;}})()`);
  fs.writeFileSync(path.join(dir,'presentation-profile.json'),JSON.stringify(layers,null,2));
  const submission=await call(`(async()=>{const original=draw,gl=R3D.context,out={diagnosticOnly:true};const sample=()=>new Promise(resolve=>{const a=[];let last=performance.now();function tick(now){a.push(now-last);last=now;if(a.length===24){a.sort((x,y)=>x-y);resolve({median:a[12],p95:a[22]});}else requestAnimationFrame(tick);}requestAnimationFrame(tick);});try{draw=()=>{original();gl.flush();};out.flush=await sample();draw=()=>{original();gl.finish();};out.finish=await sample();draw=original;out.restored=await sample();return out;}finally{draw=original;}})()`);
  fs.writeFileSync(path.join(dir,'submission-profile.json'),JSON.stringify(submission,null,2));
};
