'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),vm=require('vm'),crypto=require('crypto'),os=require('os'),{performance}=require('perf_hooks');
const root=path.resolve(__dirname,'../..'),ix=process.argv.indexOf('--source-ref'),ref=ix<0?null:process.argv[ix+1];
function fixture(){const c={JSON,console:{log(){},warn(){},error(){}},Math,Date,Promise,Map,Set,WeakMap,AbortController,setTimeout,clearTimeout};c.window=c;vm.createContext(c);for(const file of ['web/tm-agent-kernel.js','web/editor-authoring-agent-provider.js','web/editor-authoring-agent.js'])vm.runInContext(ref?cp.execFileSync('git',['show',ref+':'+file],{cwd:root,encoding:'utf8',maxBuffer:8e6}):fs.readFileSync(path.join(root,file),'utf8'),c);return c.TM.AuthoringAgent;}
const rows=[];
(async()=>{for(const file of fs.readdirSync(path.join(root,'scenarios')).filter(x=>x.endsWith('（官方）.json'))){const raw=fs.readFileSync(path.join(root,'scenarios',file)),data=JSON.parse(raw),aa=fixture(),samples=[];let bytes=0,tools=0,receiptChars=0;
 for(let i=0;i<8;i++){const draft=aa.makeDraft(data);let n=0;const start=performance.now();const r=await aa.runAuthoringLoop(draft,'修改第一名人物的忠诚',{noMemoryRecall:true,conventions:'',blockingChecks:[],maxTokens:1000000,caller:async(c,t)=>{if(++n===1){tools=t.length;bytes=JSON.stringify(t).length;return{toolCalls:[{id:'e',name:'applyEdit',input:{path:'characters[0].loyalty',value:67}}]};}return{toolCalls:[{id:'f',name:'finish',input:{summary:'仅修改忠诚'}}]};}});if(!r.finished)throw Error('fixture did not finish '+r.stopReason);receiptChars=Number(r.toolReceipts.find(x=>x.tool==='applyEdit').beforeHash.split(':')[1]);if(i)samples.push(performance.now()-start);}
 rows.push({scenario:data.id,sourceHash:crypto.createHash('sha256').update(raw).digest('hex'),characters:data.characters.length,sourceBytes:raw.length,firstToolCount:tools,firstToolSchemaChars:bytes,receiptStateChars:receiptChars,ms:samples,medianMs:samples.slice().sort((a,b)=>a-b)[3]});}
 console.log(JSON.stringify({kind:'Node full core loop with controlled immediate responses; 1 warmup +7 observations, not UI/FPS/provider latency',sourceRef:ref||'worktree',node:process.version,cpu:os.cpus()[0].model,rows},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
